# ***Estimation of GS and component biomass for forest sites which created 2020 and 2021 based on full data colection ***

# Load all data from .csv file

In [1]:
# Import main libraries

import numpy as np
import pandas as pd

In [2]:
# Load forest sites dataset
site_data = './output_other_authors_sites_biomass_20230125.xlsx'
df = pd.read_excel(site_data, sheet_name='output_2')
df.head()

,Groups,Species,Species_ID,Origin,Origin_ID,SI,A_years,H_m,DBH_cm,N_trees,...,My_R_Mst,My_R_Mcrown,My_R_Mf,My_R_Mab-g,xgb_GS,xgb_allStem,xgb_stemBark,xgb_branch,xgb_foliage,xgb_Ab_g
0,1,Alder,3,a,1.0,2,33,16.0,12.4,1700.0,...,74.209749,5.049571,2.213908,81.473227,172.530365,76.914726,12.753486,7.870040,2.562697,87.347466
1,1,Alder,3,a,1.0,-2,42,22.9,19.4,1136.0,...,170.332800,8.391685,2.493778,181.218262,418.893188,167.534470,21.907787,4.212999,1.790138,173.537598
2,2,Alder,3,a,1.0,2,33,16.0,12.4,1700.0,...,74.209749,5.049571,2.213908,81.473227,172.530365,76.914726,12.753486,7.870040,2.562697,87.347466
3,2,Alder,3,a,1.0,0,43,21.0,20.8,660.0,...,102.572743,6.356784,1.895789,110.825316,238.870056,110.138451,17.489775,10.177155,2.237852,122.553459
4,2,Alder,3,a,1.0,0,28,15.4,14.2,1369.0,...,74.175521,6.940699,2.528305,83.644525,159.462555,73.923576,11.621840,7.101619,2.530858,83.556053

In [3]:
# Information on all columns of data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 35 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Groups          857 non-null    int64
 1   Species         857 non-null    object
 2   Species_ID      857 non-null    int64
 3   Origin          856 non-null    object
 4   Origin_ID       856 non-null    float64
 5   SI              857 non-null    int64
 6   A_years         857 non-null    int64
 7   H_m             857 non-null    float64
 8   DBH_cm          856 non-null    float64
 9   N_trees         846 non-null    float64
 10  RS(P)           854 non-null    float64
 11  BA_sq_m_sq_m    857 non-null    float64
 12  GS_cub_m        857 non-null    float64
 13  ALL_STEM_t_ha   855 non-null    float64
 14  Stem_wood_t_ha  747 non-null    float64
 15  Stem_bark_t_ha  747 non-null    float64
 16  Crown_t_ha      843 non-null    float64
 17  Foliage_t_ha    854 non-null    float64
 18  Above_g_t_ha    745 non-null    float64
 19  L_M             853 non-null    float64
 20  L_Mst           853 non-null    float64
 21  L_Mcrown        853 non-null    float64
 22  L_Mf            853 non-null    float64
 23  L_Mab-g         853 non-null    float64
 24  My_R_M          856 non-null    float64
 25  My_R_Mst        856 non-null    float64
 26  My_R_Mcrown     856 non-null    float64
 27  My_R_Mf         856 non-null    float64
 28  My_R_Mab-g      856 non-null    float64
 29  xgb_GS          857 non-null    float64
 30  xgb_allStem     857 non-null    float64
 31  xgb_stemBark    857 non-null    float64
 32  xgb_branch      857 non-null    float64
 33  xgb_foliage     857 non-null    float64
 34  xgb_Ab_g        857 non-null    float64
dtypes: float64(29), int64(4), object(2)
memory usage: 234.5+ KB

In [4]:
# Selecting main working parameters

select = pd.DataFrame(df, columns= ['Species_ID', 'Origin_ID', 'H_m', 'DBH_cm', 'BA_sq_m_sq_m'])
'''
In the "ID_species" column: "0" is Pine, "1" is Spruce, "2" is Birch, "3" is Alder, 
"4" is Aspen, "5" is Oak
In the "ID_origin" column: "0" is nutural stand, "1" is artificial stand
'''

# Show the first five columns
select.head()

   Species_ID  Origin_ID   H_m  DBH_cm  BA_sq_m_sq_m
0           3        1.0  16.0    12.4          20.6
1           3        1.0  22.9    19.4          33.5
2           3        1.0  16.0    12.4          20.6
3           3        1.0  21.0    20.8          22.4
4           3        1.0  15.4    14.2          21.7

# Review of input data for classification

In [5]:
# Information on all columns of data frame
select.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 857 entries, 0 to 856
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Species_ID    857 non-null    int64
 1   Origin_ID     856 non-null    float64
 2   H_m           857 non-null    float64
 3   DBH_cm        856 non-null    float64
 4   BA_sq_m_sq_m  857 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 33.6 KB

In [6]:
# Descriptive statistics of main parameters
select.describe()

       Species_ID   Origin_ID         H_m      DBH_cm  BA_sq_m_sq_m
count  857.000000  856.000000  857.000000  856.000000    857.000000
mean     1.529755    0.279206   16.452275   17.132243     26.329988
std      1.823872    0.448871    7.039954   10.439115     10.629993
min      0.000000    0.000000    1.500000    1.100000      1.000000
25%      0.000000    0.000000   11.200000    9.900000     19.000000
50%      0.000000    0.000000   16.100000   15.500000     26.800000
75%      3.000000    1.000000   21.200000   22.100000     34.500000
max      5.000000    1.000000   38.300000   94.000000     51.500000

# Selecting working columns for the XGBoost algorithms

In [7]:
# We select independent variables and predicting parameter 
X = select

In [8]:
# Columns in "X" data collections
X.head()

   Species_ID  Origin_ID   H_m  DBH_cm  BA_sq_m_sq_m
0           3        1.0  16.0    12.4          20.6
1           3        1.0  22.9    19.4          33.5
2           3        1.0  16.0    12.4          20.6
3           3        1.0  21.0    20.8          22.4
4           3        1.0  15.4    14.2          21.7

# Load XGBoost module and learned model for predict of species and other lands

In [9]:
#  Importing the main library for building model and its analysis

import xgboost as xgb
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [10]:
# Load learned models

xgb_model_GS = xgb.XGBRegressor()
xgb_model_allStem = xgb.XGBRegressor()
xgb_model_stemBark = xgb.XGBRegressor()
xgb_model_br = xgb.XGBRegressor()
xgb_model_f = xgb.XGBRegressor()
xgb_model_LN_GS = xgb.XGBRegressor()
xgb_model_LN_allStem = xgb.XGBRegressor()
xgb_model_LN_stemBark = xgb.XGBRegressor()
xgb_model_LN_br = xgb.XGBRegressor()
xgb_model_LN_f = xgb.XGBRegressor()
xgb_model_GS.load_model('./XGBoost_models/01_CS_other_authors_XGB_model.json')
xgb_model_allStem.load_model('./XGBoost_models/02_M_all_stem_other_authors_XGB_model.json')
xgb_model_stemBark.load_model('./XGBoost_models/03_M_stem_bark_other_authors_XGB_model.json')
xgb_model_br.load_model('./XGBoost_models/04_M_branch_other_authors_XGB_model.json')
xgb_model_f.load_model('./XGBoost_models/05_M_foliage_other_authors_XGB_model.json')
xgb_model_LN_GS.load_model('./XGBoost_models/01_LN_CS_other_authors_XGB_model.json')
xgb_model_LN_allStem.load_model('./XGBoost_models/02_LN_M_all_stem_other_authors_XGB_model.json')
xgb_model_LN_stemBark.load_model('./XGBoost_models/03_LN_M_stem_bark_other_authors_XGB_model.json')
xgb_model_LN_br.load_model('./XGBoost_models/04_LN_M_branch_other_authors_XGB_model.json')
xgb_model_LN_f.load_model('./XGBoost_models/05_LN_M_foliage_other_authors_XGB_model.json')

In [11]:
# Show all parameters of XGBoost models

print(xgb_model_GS)
print(xgb_model_allStem)
print(xgb_model_stemBark)
print(xgb_model_br)
print(xgb_model_f)
print(xgb_model_LN_GS)
print(xgb_model_LN_allStem)
print(xgb_model_LN_stemBark)
print(xgb_model_LN_br)
print(xgb_model_LN_f)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.8821030853351247,
             enable_categorical=False, eval_metric=['rmse'],
             gamma=0.011864622396297486, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.1209976158148326,
             max_delta_step=0, max_depth=4, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=178, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=0.5339951896800694,
             tree_method='auto', validate_parameters=1, verbosity=None)
XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.8944536735419889,
             enable_categorical=False, eval_metric=['rmse'],
             gamma=0.04791876153524799, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.10132522643422313,
             max_delta_step=0, max_depth=3, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=108, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=0.7379908073261374,
             tree_method='auto', validate_parameters=1, verbosity=None)
XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.8942960625751492,
             enable_categorical=False, eval_metric=['rmse'],
             gamma=0.27892087021094436, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.11832141467878397,
             max_delta_step=0, max_depth=3, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=197, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=0.7296434500976409,
             tree_method='auto', validate_parameters=1, verbosity=None)
XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.719687164452369,
             enable_categorical=False, eval_metric=['rmse'],
             gamma=0.10222336734225579, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.11773373525204708,
             max_delta_step=0, max_depth=4, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=196, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=0.6012141949508016,
             tree_method='auto', validate_parameters=1, verbosity=None)
XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=0.6376420855691677,
             enable_categorical=False, eval_metric=['rmse'],
             gamma=0.030051961019074536, gpu_id=-1, importance_type=None,
             interaction_constraints='', learning_rate=0.2640899209518656,
             max_delta_step=0, max_depth=4, min_child_weight=1, missing=nan,
             monotone_constraints='()', n_estimators=196, n_jobs=4,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, scale_pos_weight=1, subsample=0.7879876518750124,
             tree_method='auto', validate_parameters=1, verbosity=None)

In [12]:
# Create predict values

pred_GS = xgb_model_GS.predict(X, ntree_limit=xgb_model_GS.best_ntree_limit)
pred_allStem = xgb_model_allStem.predict(X, ntree_limit=xgb_model_allStem.best_ntree_limit)
pred_stemBark = xgb_model_stemBark.predict(X, ntree_limit=xgb_model_stemBark.best_ntree_limit)
pred_br = xgb_model_br.predict(X, ntree_limit=xgb_model_br.best_ntree_limit)
pred_f = xgb_model_f.predict(X, ntree_limit=xgb_model_f.best_ntree_limit)
pred_LN_GS = xgb_model_LN_GS.predict(X, ntree_limit=xgb_model_GS.best_ntree_limit)
pred_LN_allStem = xgb_model_LN_allStem.predict(X, ntree_limit=xgb_model_allStem.best_ntree_limit)
pred_LN_stemBark = xgb_model_LN_stemBark.predict(X, ntree_limit=xgb_model_stemBark.best_ntree_limit)
pred_LN_br = xgb_model_LN_br.predict(X, ntree_limit=xgb_model_br.best_ntree_limit)
pred_LN_f = xgb_model_LN_f.predict(X, ntree_limit=xgb_model_f.best_ntree_limit)

/home/dima/anaconda3/lib/python3.8/site-packages/xgboost/core.py:105: UserWarning: ntree_limit is deprecated, use `iteration_range` or model slicing instead.
  warnings.warn(

In [13]:
# Convert predicted parameters to real values

R_pred_GS = np.exp(pred_LN_GS)
R_pred_allStem = np.exp(pred_LN_allStem)
R_pred_stemBark = np.exp(pred_LN_stemBark)
R_pred_br = np.exp(pred_LN_br)
R_pred_f = np.exp(pred_LN_f)

In [14]:
data = {'xgb_GS_ver2':pred_GS, 'xgb_allStem_ver2':pred_allStem, 'xgb_stemBark_ver2':pred_stemBark, 'xgb_branch_ver2':pred_br, 'xgb_foliage_ver2':pred_f, 'T_ln_xgb_GS_ver2':R_pred_GS, 'T_ln_xgb_allStem_ver2':R_pred_allStem, 'T_ln_xgb_stemBark_ver2':R_pred_stemBark, 'T_ln_xgb_branch_ver2':R_pred_br, 'T_ln_xgb_foliage_ver2':R_pred_f}

In [15]:
# Add predicted values to the working dataframe
pred = pd.DataFrame(data)

In [16]:
# Show output data of biomass components
print(pred)

     Ln_xgb_GS  Ln_xgb_allStem  Ln_xgb_stemBark  Ln_xgb_branch  \
0     5.140347        4.326847         2.392613       1.930532
1     5.988477        5.154976         3.195204       1.898181
2     5.140347        4.326847         2.392613       1.930532
3     5.429177        4.663519         2.764480       2.172356
4     5.130596        4.341617         2.434403       2.056040
..         ...             ...              ...            ...
852   4.967692        4.230946         2.667916       2.902785
853   5.536481        4.791327         3.180760       2.896634
854   5.797106        5.008728         3.266805       3.191193
855   6.032084        5.305983         3.741702       3.240403
856   6.127394        5.323916         3.819647       3.595645

     Ln_xgb_foliage  T_ln_xgb_GS  T_ln_xgb_allStem  T_ln_xgb_stemBark  \
0          0.718511   170.774933         75.705215          10.942053
1          0.612538   398.806671        173.291626          24.415154
2          0.718511   170.774933         75.705215          10.942053
3          0.841122   227.961624        106.008514          15.870779
4          0.678623   169.117905         76.831680          11.409010
..              ...          ...               ...                ...
852        2.993153   143.694916         68.782272          14.409905
853        2.882795   253.783463        120.461113          24.065039
854        2.342229   329.344971        149.714111          26.227407
855        2.510179   416.582092        201.539032          42.169704
856        2.224994   458.240295        205.185806          45.588127

     T_ln_xgb_branch  T_ln_xgb_foliage
0           6.893176          2.051377
1           6.673744          1.845109
2           6.893176          2.051377
3           8.778940          2.318966
4           7.814958          1.971162
..               ...               ...
852        18.224833         19.948483
853        18.113081         17.864140
854        24.317423         10.404404
855        25.544018         12.307131
856        36.439194          9.253431

[857 rows x 10 columns]

In [17]:
# Show description statistics

pred.describe()

,Ln_xgb_GS,Ln_xgb_allStem,Ln_xgb_stemBark,Ln_xgb_branch,Ln_xgb_foliage,T_ln_xgb_GS,T_ln_xgb_allStem,T_ln_xgb_stemBark,T_ln_xgb_branch,T_ln_xgb_foliage
count,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000,857.000000
mean,5.166968,4.342050,2.161755,2.314026,1.362265,228.242706,101.499664,11.219790,12.692572,4.610232
std,0.835738,0.857159,0.763399,0.657023,0.622703,142.161331,66.323662,8.361879,10.248746,2.488325
min,1.081797,0.790769,-0.859796,0.082224,-1.420957,2.949975,2.205091,0.423248,1.085699,0.241483
25%,4.745595,3.886847,1.820216,1.930532,0.988928,115.076256,48.756916,6.173193,6.893176,2.688351
50%,5.329025,4.554136,2.193877,2.325948,1.460269,206.236755,95.024643,8.969920,10.236380,4.307118
75%,5.777792,4.928813,2.632865,2.621749,1.823859,323.045105,138.215286,13.913574,13.759770,6.195722
max,6.578265,5.840845,3.822549,4.143004,2.993153,719.290100,344.069824,45.720596,62.991791,19.948483

In [18]:
# Add predicted values to the working dataframe

df = df.join(pred)

In [19]:
# Calculating the sum of above-ground biomass using the XGBoost algorithm

sum_biomass = df['xgb_allStem'] + df['xgb_branch'] + df['xgb_foliage']
df['T_ln_xgb_Ab_g'] = sum_biomass

ln_sum_biomass = df['T_ln_xgb_allStem'] + df['T_ln_xgb_branch'] + df['T_ln_xgb_foliage']
df['T_ln_xgb_Ab_g_ver2'] = ln_sum_biomass

In [20]:
# Save new dataframe with predict values to .xlsx-file

df.to_excel('./Est_biomass_use_final_models.xlsx', sheet_name='output', index=False)